package dtu.fts.automotivesimulator.entity.enumeration;

public enum LogType {

	TASK_READY,
	TASK_EXECUTING,
	TASK_FINISHED,
	TASK_INTERRUPTED,
	TASK_WAITING,
	DEADLINE_MISSED,
	START_IDLE,
	FINISH_IDLE,
	MESSAGE_SENT,
	MESSAGE_RECEIVED,
	APPLICATION_START,
	APPLICATION_FINISHED
	
}
